import { Link } from "react-router-dom";

/**
 * Public landing page.
 *
 * Renders entirely from static content and makes no API calls, because it is
 * what GitHub Pages serves — where no backend exists. Everything below is
 * written to be honest about what the system does and does not do; the
 * Limitations section is deliberately as prominent as the Features section.
 */

const FEATURES = [
  {
    label: "Deterministic numbers",
    title: "The model picks metrics. It never computes them.",
    body: "A question is compiled into a typed plan — a DAG of registered Python metrics. The planner chooses what to measure and never sees a value; the executor computes; a second pass writes prose over those results under a no-arithmetic rule.",
  },
  {
    label: "Verification",
    title: "Every number in the prose is checked",
    body: "A deterministic pass re-reads the finished thesis, extracts each numeric claim, and compares it against the snapshot. Claims it cannot map are reported as unverifiable — never as passing.",
  },
  {
    label: "Reproducibility",
    title: "Runs are recorded and diffable",
    body: "Each analysis persists its snapshot, prompts, model parameters and output. Two runs with identical inputs should agree; when they do not, that divergence is surfaced rather than averaged away.",
  },
  {
    label: "Provenance",
    title: "You can see which source answered",
    body: "Providers disagree on split adjustment, fiscal alignment and currency. Every fetch records who answered, whether it came from cache, and how the payload verified — frequency, coverage, units.",
  },
  {
    label: "Methodology memory",
    title: "Corrections of method, not of answers",
    body: "Teach the system how to approach a problem and later runs apply it. Notes containing prices or scores are rejected: a stored number would be replayed onto runs where it is no longer true.",
  },
  {
    label: "Local first",
    title: "Runs on your machine, no API keys",
    body: "Ollama serves the model locally. Market data comes from keyless providers by default, and the portfolio lives in a SQLite file you own.",
  },
];

const PIPELINE = [
  { step: "Snapshot", detail: "Market data fetched once, frozen, content-addressed" },
  { step: "Planner", detail: "Chooses metrics from a fixed catalog — sees no values" },
  { step: "Executor", detail: "Plain Python computes every figure" },
  { step: "Narrator", detail: "Writes prose over computed results only" },
  { step: "Harness", detail: "Validates, verifies claims, overrides the conviction score" },
  { step: "Run record", detail: "Persisted for replay and comparison" },
];

const LIMITATIONS = [
  {
    title: "This is not investment advice",
    body: "It is a research tool. Output is generated by a language model over public data and can be wrong in ways that read perfectly plausibly. Nothing here is a recommendation to buy or sell anything.",
  },
  {
    title: "Verification has real gaps",
    body: "Numeric claims are only checked for metrics the verifier knows about. Anything outside that set counts as unverifiable, not verified. Qualitative claims are not checked at all.",
  },
  {
    title: "Scoring bands are absolute",
    body: "Valuation scoring uses fixed thresholds rather than sector-relative ones, so a utility and a software company are judged on the same scale. Treat the composite as a starting point, not a verdict.",
  },
  {
    title: "Determinism is bounded",
    body: "Sampling is greedy and seeded and every input is recorded, but model providers do not guarantee identical output. The plan pipeline narrows this by moving arithmetic out of the model — it does not eliminate it.",
  },
  {
    title: "Data quality is inherited",
    body: "Fundamentals come from third-party providers that disagree with each other and are sometimes stale or wrong. Provenance tells you which source answered; it cannot tell you that source was right.",
  },
  {
    title: "Committee mode is not yet audited",
    body: "Persona analyses run with full freedom rather than as weightings over computed dimensions, so their conviction scores are not reproducible the way the plan pipeline's are.",
  },
];

function Section({
  id,
  eyebrow,
  title,
  children,
}: {
  id: string;
  eyebrow: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} className="border-t border-border/60 py-16 sm:py-20">
      <p className="text-xs font-medium uppercase tracking-[0.18em] text-accent-blue/80">
        {eyebrow}
      </p>
      <h2 className="mt-3 text-2xl font-semibold tracking-tight text-white sm:text-3xl">
        {title}
      </h2>
      <div className="mt-8">{children}</div>
    </section>
  );
}

export function Landing() {
  return (
    <div className="min-h-screen bg-surface text-gray-300">
      <header className="sticky top-0 z-20 border-b border-border/60 bg-surface/85 backdrop-blur">
        <nav className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <span className="text-lg font-bold tracking-tight text-white">MJ Research</span>
          <div className="flex items-center gap-6 text-sm">
            <a href="#features" className="hidden text-gray-500 transition-colors hover:text-gray-200 sm:block">
              Features
            </a>
            <a href="#architecture" className="hidden text-gray-500 transition-colors hover:text-gray-200 sm:block">
              Architecture
            </a>
            <a href="#limitations" className="hidden text-gray-500 transition-colors hover:text-gray-200 sm:block">
              Limitations
            </a>
            <Link
              to="/dashboard"
              className="rounded-lg bg-accent-blue px-3.5 py-1.5 font-medium text-white transition-colors hover:bg-blue-500"
            >
              Open app
            </Link>
          </div>
        </nav>
      </header>

      <main className="mx-auto max-w-5xl px-6">
        {/* Hero */}
        <div className="py-20 sm:py-28">
          <p className="text-xs font-medium uppercase tracking-[0.18em] text-accent-blue/80">
            Local-first equity research
          </p>
          <h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-[1.1] tracking-tight text-white sm:text-5xl">
            Research where the numbers come from code, not from the model.
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-relaxed text-gray-400">
            Most AI research tools hand a language model a pile of data and ask for a verdict,
            which makes every figure in the answer a token prediction. This one compiles the
            question into a typed program, computes the figures in Python, and lets the model
            write only over results it did not produce.
          </p>
          <div className="mt-9 flex flex-wrap items-center gap-3">
            <Link
              to="/dashboard"
              className="rounded-lg bg-accent-blue px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-blue-500"
            >
              Open the app
            </Link>
            <a
              href="https://github.com/karanmjpinto/ai-hedge-fund"
              target="_blank"
              rel="noreferrer"
              className="rounded-lg border border-border-light px-5 py-2.5 text-sm font-medium text-gray-300 transition-colors hover:border-gray-600 hover:text-white"
            >
              View source
            </a>
          </div>
          <p className="mt-6 text-sm text-gray-600">
            Requires a local backend and{" "}
            <a href="https://ollama.com" target="_blank" rel="noreferrer" className="text-gray-500 underline underline-offset-4 hover:text-gray-300">
              Ollama
            </a>
            . Nothing is hosted — your portfolio and your model stay on your machine.
          </p>
        </div>

        {/* About */}
        <Section id="about" eyebrow="About" title="What this is">
          <div className="grid gap-8 sm:grid-cols-2">
            <p className="leading-relaxed text-gray-400">
              A research and portfolio workstation for a single investor. It pulls market data
              from several providers with fallback and caching, keeps a persistent book in
              SQLite, runs rule-based backtests and portfolio construction, and produces written
              investment theses using a language model running locally.
            </p>
            <p className="leading-relaxed text-gray-400">
              The design goal is not a smarter model. It is a harness around the model good
              enough that its output can be checked, repeated, and argued with — so that when
              an answer is wrong, you can tell, and fix the method rather than the number.
            </p>
          </div>
        </Section>

        {/* Features */}
        <Section id="features" eyebrow="Features" title="What it does">
          <div className="grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-2">
            {FEATURES.map((f) => (
              <article key={f.label} className="bg-surface-card p-6">
                <p className="text-xs font-medium uppercase tracking-wider text-gray-600">
                  {f.label}
                </p>
                <h3 className="mt-2.5 text-base font-semibold text-white">{f.title}</h3>
                <p className="mt-2.5 text-sm leading-relaxed text-gray-400">{f.body}</p>
              </article>
            ))}
          </div>
        </Section>

        {/* Architecture */}
        <Section id="architecture" eyebrow="Architecture" title="How a question becomes an answer">
          <ol className="space-y-px overflow-hidden rounded-xl border border-border bg-border">
            {PIPELINE.map((p, i) => (
              <li key={p.step} className="flex items-baseline gap-4 bg-surface-card px-6 py-4">
                <span className="font-mono text-xs text-gray-600">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span className="w-28 shrink-0 text-sm font-medium text-white">{p.step}</span>
                <span className="text-sm leading-relaxed text-gray-400">{p.detail}</span>
              </li>
            ))}
          </ol>
          <p className="mt-6 max-w-3xl text-sm leading-relaxed text-gray-500">
            The model appears twice, in two narrow roles, and is never the source of a figure.
            When the plan computes a conviction score it replaces whatever the narrator wrote,
            and the substitution is reported rather than hidden.
          </p>
        </Section>

        {/* Limitations */}
        <Section id="limitations" eyebrow="Limitations" title="What it does not do">
          <div className="grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-2">
            {LIMITATIONS.map((l) => (
              <article key={l.title} className="bg-surface-card p-6">
                <h3 className="text-base font-semibold text-white">{l.title}</h3>
                <p className="mt-2.5 text-sm leading-relaxed text-gray-400">{l.body}</p>
              </article>
            ))}
          </div>
        </Section>
      </main>

      <footer className="border-t border-border/60 py-10">
        <div className="mx-auto flex max-w-5xl flex-col gap-3 px-6 text-sm text-gray-600 sm:flex-row sm:items-center sm:justify-between">
          <span>A personal research tool. Not investment advice.</span>
          <a
            href="https://github.com/karanmjpinto/ai-hedge-fund"
            target="_blank"
            rel="noreferrer"
            className="transition-colors hover:text-gray-400"
          >
            github.com/karanmjpinto/ai-hedge-fund
          </a>
        </div>
      </footer>
    </div>
  );
}
